# MAE optimization further improves LPC parameters iteratively from the result
# of direct MSE by minimizing mean-absolute-error.
# This is (currently) computationally prohibitive for inputs with realistic
# lengths.

block_sizes = [2048]

[subframe_coding.qlpc]
use_direct_mse = true
mae_optimization_steps = 8

[subframe_coding.qlpc.window]
type = "Rectangle"
