[package]
name = "flacenc-rs"
version = "0.1.0"
description = "FLAC encoder written in Rust."
readme = "README.md"
license = "Apache-2.0"
edition = "2021"
keywords = ["flac", "lossless", "encoder", "audio"]
categories = ["compression", "multimedia::audio", "multimedia::encoding"]

# This is for enabling use of profilers with a release build.
[profile.release]
debug = 1

[dependencies]
bitvec = "1.0.0"
clap = { version = "3.1.8", features = ["derive"] }
crc = "2.1"
derive_more = "0.99.17"
heapless = "0.7.10"
md5 = "0.7.0"
once_cell = "1.10.0"
seq-macro = "0.3"
serde = { version = "1.0", features = ["derive"] }
sndfile = "0.0"
toml = "0.5"

[dev-dependencies]
parameterized = "1.0.0"
rand = "0.8.5"
tempfile = "3"
